apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: client-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: client-pod
    spec:
      containers:
      - name: client-pod
        image: pash7e7/project_client
        ports:
        - containerPort: 3000