apiVersion: v1
kind: Service
metadata:
  name: avatar-postgres-svc
spec:
  ports:
    - port: 80
      targetPort: 5432
  selector:
    app: avatar-postgres-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avatar-postgres-deployment
spec:
  selector:
    matchLabels:
      app: avatar-postgres-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: avatar-postgres-pod
    spec:
      containers:
      - name: avatar-postgres-pod
        image: postgres:14.2-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: "schedule"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "qwerty"
